name: Get Latest Tag
description: Get the latest tag from the repository

outputs:
    tag-name:
        description: The latest tag name
        value: ${{ steps.get-latest-tag.outputs.tag-name }}

runs:
    using: "composite"
    steps:
        - run: echo "tag-name=$(git fetch --prune && git describe --tags $(git rev-list --tags --max-count=1) | cut -c 2-)" >> $GITHUB_OUTPUT
          shell: bash
          id: get-latest-tag