# This file is automatically generated by https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/homebrew-release.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/templates/homebrew-tfs.rb
class Tfs < Formula
    desc "Everything you need to get started with TFS"
    homepage "https://trytfs.com"
    url "__CLI_MAC_INTEL_DOWNLOAD_URL__"
    sha256 "__CLI_MAC_INTEL_SHA256__"
    version "__CLI_VERSION__"
    version_scheme 1
  
    on_macos do
      on_arm do
        url "__CLI_MAC_ARM_DOWNLOAD_URL__"
        sha256 "__CLI_MAC_ARM_SHA256__"
      end
    end
  
    on_linux do
      on_intel do
        url "__CLI_LINUX_DOWNLOAD_URL__"
        sha256 "__CLI_LINUX_SHA256__"
      end
      on_arm do
        url "__CLI_LINUX_ARM_DOWNLOAD_URL__"
        sha256 "__CLI_LINUX_ARM_SHA256__"
      end
    end
  
    def install
      inreplace "bin/tfs", /^CLIENT_HOME=/, "export TFS_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
      libexec.install Dir["*"]
      bin.install_symlink libexec/"bin/tfs"
    end
  
    def caveats; <<~EOS
      To use the TFS CLI's autocomplete --
        Via homebrew's shell completion:
          1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
              NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                    and called, either explicitly or via a framework like oh-my-zsh.
          2) Then run
            $ tfs autocomplete --refresh-cache
        OR
        Use our standalone setup:
          1) Run and follow the install steps:
            $ tfs autocomplete
    EOS
    end
  
    test do
      system bin/"tfs", "version"
    end
  end