#!/usr/bin/env bash

set -e

if [[ "${CI:-}" != "true" ]]; then
  echo "skipping github setup since not on CI"
  exit
fi

git config --global user.email "77931978+iamolayemi@users.noreply.github.com"
git config --global user.name "iamolayemi"