name: Create CLI Release

on:
    workflow_dispatch:

env:
    HUSKY: 0

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    test:
        name: Run Unit Tests
        uses: ./.github/workflows/unit-test.yml

    release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    tarballs-release:
        name: Tarballs Release
        needs: [release]
        uses: ./.github/workflows/tarballs-release.yml
        secrets: inherit

    package-manager-release:
        name: Package Manager Release
        needs: [tarballs-release]
        uses: ./.github/workflows/package-manager-release.yml
        secrets: inherit

    executable-release:
        name: Executable Release
        needs: [release]
        uses: ./.github/workflows/executable-release.yml
        secrets: inherit

    promote-s3-releases:
        name: Promote S3 Releases
        needs: [tarballs-release, executable-release]
        uses: ./.github/workflows/promote-s3-releases.yml
        secrets: inherit

    notify-complete-success:
        if: ${{ success() }}
        needs: [release, package-manager-release, promote-s3-releases]
        name: Notify Release Success
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#36a64f'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS ClI'
                  SLACK_MESSAGE: 'CLI Release Workflow Completed Successfully'
                  SLACK_FOOTER: Posted automatically using GitHub Actions

    notify-complete-fail:
        if: ${{ failure() || cancelled() }}
        needs: [release, promote-s3-releases]
        name: Notify Release Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#ff3333'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS ClI'
                  SLACK_MESSAGE: 'CLI Release Workflow Failed'
                  SLACK_FOOTER: Posted automatically using GitHub Actions
