name: Create CLI Release

on:
    release:
        types: [released]
env:
    HUSKY: 0

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    npm-release:
        name: NPM Release
        uses: ./.github/workflows/npm-release.yml
        secrets: inherit

    tarballs-release:
        name: Tarballs Release
        uses: ./.github/workflows/tarballs-release.yml
        secrets: inherit

    homebrew-release:
        name: Homebrew Release
        needs: [tarballs-release]
        uses: ./.github/workflows/homebrew-release.yml
        secrets: inherit

    executable-release:
        name: Executable Release
        uses: ./.github/workflows/executable-release.yml
        secrets: inherit

    promote-s3-releases:
        name: Promote S3 Releases
        needs: [tarballs-release, executable-release]
        uses: ./.github/workflows/promote-s3-releases.yml
        secrets: inherit

    notify-complete-success:
        if: ${{ success() }}
        needs: [npm-release, homebrew-release, promote-s3-releases]
        name: Notify Release Success
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#36a64f'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS ClI'
                  SLACK_MESSAGE: 'CLI Release Workflow Completed Successfully'
                  SLACK_FOOTER: Posted automatically using GitHub Actions

    notify-complete-fail:
        if: ${{ failure() || cancelled() }}
        needs: [npm-release, homebrew-release, promote-s3-releases]
        name: Notify Release Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#ff3333'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS ClI'
                  SLACK_MESSAGE: 'CLI Release Workflow Failed'
                  SLACK_FOOTER: Posted automatically using GitHub Actions
