name: Darwin Executable Release

on:
    workflow_call:
        inputs:
            cli_name:
                type: string
                description: 'The name of the CLI'
                default: 'tfs'
                required: false
    workflow_dispatch:
        inputs:
            cli_name:
                type: string
                description: 'The name of the CLI'
                default: 'tfs'
                required: false

jobs:
    pack-darwin-executable:
        name: Pack Darwin Executable
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: yarn
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Pack MacOS Executable
              run: yarn pack:macos
            - uses: actions/upload-artifact@v3
              with:
                  name: packed-darwin-executable
                  path: dist/macos
                  retention-days: 3

    upload-darwin-executable:
        name: Upload Darwin Executable
        needs: [pack-darwin-executable]
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: yarn
            - uses: actions/download-artifact@v3
              with:
                  name: packed-darwin-executable
                  path: dist/macos
            - name: List all the downloaded files (for debugging)
              run: ls -R
              working-directory: dist/macos
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Upload Binaries to S3
              run: yarn upload:macos

    upload-darwin-executable-github:
        name: Upload Darwin Executable to Github
        needs: [pack-darwin-executable]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v3
              with:
                  name: packed-darwin-executable
                  path: dist/macos
            - name: List all the downloaded files (for debugging)
              run: ls -R
              working-directory: dist/macos
            - name: Get Latest SHA
              uses: ./.github/actions/get-latest-sha
              id: get-sha
            - name: Get Latest Tag
              uses: ./.github/actions/get-latest-tag
              id: get-tag
            - name: Upload Binaries to Github (arm64)
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: |
                      dist/macos/${{ inputs.cli_name }}-v${{ steps.get-tag.outputs.tag-name }}-${{ steps.get-sha.outputs.sha-short }}-arm64.pkg
                  tag: v${{ steps.get-tag.outputs.tag-name }}
                  asset_name: ${{ inputs.cli_name }}_v${{ steps.get-tag.outputs.tag-name }}_darwin-arm64.pkg
                  overwrite: true
            - name: Upload Binaries to Github (x64)
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: |
                      dist/macos/${{ inputs.cli_name }}-v${{ steps.get-tag.outputs.tag-name }}-${{ steps.get-sha.outputs.sha-short }}-x64.pkg
                  tag: v${{ steps.get-tag.outputs.tag-name }}
                  asset_name: ${{ inputs.cli_name }}_v${{ steps.get-tag.outputs.tag-name }}_darwin-x64.pkg
                  overwrite: true

    notify-complete-fail:
        if: ${{ failure() || cancelled() }}
        needs: [upload-darwin-executable, upload-darwin-executable-github]
        name: Notify Release Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#ff3333'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS CLI'
                  SLACK_MESSAGE: 'Darwin Executable Release Failed'
                  MSG_MINIMAL: actions url
                  SLACK_FOOTER: Posted automatically using GitHub Actions
