name: Get Latest SHA

on:
    workflow_call:

jobs:
    get-latest-sha:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - id: get-latest-sha
              run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        outputs:
            SHORT_SHA: ${{ steps.get-latest-sha.outputs.SHORT_SHA }}
