name: Publish Package to NPM

on:
    workflow_call:

jobs:
    npm-build-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@ownage-fdt'
                  cache: yarn
            - name: Install Dependencies
              run: yarn install --network-timeout 600000
            - name: Build The Package
              run: yarn build
            - name: Publish The Package
              run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    notify-complete-fail:
        if: ${{ failure() || cancelled() }}
        needs: [npm-build-release]
        name: Notify Release Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout The Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#ff3333'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS ClI'
                  SLACK_MESSAGE: 'NPM Release Failed'
                  MSG_MINIMAL: actions url
