name: Tarballs Release

on:
    workflow_call:
    workflow_dispatch:

jobs:
    pack-tarballs:
        name: Pack Tarballs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: yarn
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Build and Pack Tarballs
              run: yarn pack:tarballs
            - uses: actions/upload-artifact@v3
              with:
                  name: packed-tarballs
                  path: dist
                  retention-days: 3

    upload-tarballs:
        name: Upload Tarballs
        needs: [pack-tarballs]
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: yarn
            - uses: actions/download-artifact@v3
              with:
                  name: packed-tarballs
                  path: /dist
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Upload Tarballs
              run: yarn upload:tarballs

    notify-complete-fail:
        if: ${{ failure() || cancelled() }}
        needs: [upload-tarballs]
        name: Notify Release Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: '#ff3333'
                  SLACK_USERNAME: CLI Release Bot
                  SLACK_ICON_EMOJI: ':ship:'
                  SLACK_TITLE: 'TFS CLI'
                  SLACK_MESSAGE: 'Tarballs Release Failed'
                  MSG_MINIMAL: actions url
