name: Create Test Release

on:
    workflow_dispatch:

env:
    HUSKY: 0

permissions:
    contents: write

jobs:
    test-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create Test Release
              run: |
                  echo "Test Release"

    tarballs-release:
        name: Tarballs Release
        needs: [test-release]
        uses: ./.github/workflows/tarballs-release.yml
        secrets: inherit

    package-manager-release:
        name: Package Manager Release
        needs: [test-release]
        uses: ./.github/workflows/package-manager-release.yml
        secrets: inherit

    # promote-s3-releases:
    #     needs: [tarballs-release, executatble-release]
    #     uses: ./.github/workflows/promote-s3-releases.yml
    #     secrets: inherit
