name: tests
on:
    push:
        branches-ignore: [main]
    pull_request:
    workflow_call:

jobs:
    test:
        strategy:
            matrix:
                os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
                node_version: [lts/-1, lts/*, latest]
            fail-fast: false
        name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node_version }}
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Setup Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: yarn
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Run Unit Tests
              run: yarn test

    notify-complete-fail:
        if: ${{ failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        needs: [test]
        name: Notify Test Failed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_COLOR: 'danger'
                  SLACK_USERNAME: CLI Github Actions
                  SLACK_ICON_EMOJI: ':github:'
                  SLACK_TITLE: 'TFS CLI'
                  SLACK_MESSAGE: 'CLI Tests Failed'
                  MSG_MINIMAL: actions url
                  SLACK_FOOTER: Posted automatically using GitHub Actions
