name: Windows Executable Release

on:
    workflow_dispatch:

env:
    CLI_NAME: 'tfs'

jobs:
    get-sha:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Get Latest SHA
              id: get-sha
              run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        outputs:
            SHORT_SHA: ${{ steps.get-sha.outputs.SHORT_SHA }}

    get-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Get Latest Tag
              id: get-tag
              run: |
                  git fetch --prune --unshallow
                  echo "TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT
        outputs:
            TAG_NAME: ${{ steps.get-tag.outputs.TAG_NAME }}

    pack-windows-release:
        runs-on: ubuntu-latest
        needs: [get-tag, get-sha]
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: yarn
            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@master
            - name: Install Homebrew Dependencies
              run: brew install nsis
            - name: Install Node Dependencies
              run: yarn install --network-timeout 600000
            - name: Pack Windows Executable
              run: yarn pack:win
            - name: Upload Artifact (x64)
              uses: actions/upload-artifact@v3
              with:
                  name: ${{env.CLI_NAME}}-${{ needs.get-tag.outputs.TAG_NAME }}-x64.exe
                  path: dist/win32/${{env.CLI_NAME}}-${{ needs.get-tag.outputs.TAG_NAME }}-${{ needs.get-sha.outputs.SHORT_SHA }}-x64.exe
                  retention-days: 3
            - name: Upload Artifact (x86)
              uses: actions/upload-artifact@v3
              with:
                  name: ${{env.CLI_NAME}}-${{ needs.get-tag.outputs.TAG_NAME }}-x86.exe
                  path: dist/win32/${{env.CLI_NAME}}-${{ needs.get-tag.outputs.TAG_NAME }}-${{ needs.get-sha.outputs.SHORT_SHA }}-x86.exe
                  retention-days: 3
